config/routes.rb
Rails.application.routes.draw do
  root 'invoices#index'

  get 'help' => 'help#index'

  get 'customers', to: 'customers#index'

  get 'invoices/:id/download_csv', to: 'invoices#download_csv', as: 'invoices_download_csv'
  get 'invoices/:id/download_xml', to: 'invoices#download_xml', as: 'invoices_download_xml'
  get 'invoices/:id/download_xsig', to: 'invoices#download_xsig', as: 'invoices_download_xsig'
  get 'invoices/:id/send', to: 'invoices#send_to_admin', as: 'invoices_send_to_admin'
  get 'invoices/:id/sign', to: 'invoices#sign', as: 'invoices_sign'
  post 'invoices/:id/sign', to: 'invoices#signing', as: 'invoices_signing'
  get 'invoices/:id/render_pdf', to: 'invoices#render_pdf', as: 'invoices_render_pdf'
  resources :invoices, except: [:update, :edit]

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
end

app/models/invoice.rb
# == Schema Information
#
# Table name: invoices
#
#  id            :integer          not null, primary key
#  issuer_id     :integer
#  customer_id   :integer
#  invoice_serie :string           default("")
#  invoice_num   :string
#  invoice_date  :date
#  subject       :string
#  amount        :decimal(11, 2)   default("0")
#  csv           :text
#  xml           :text
#  xsig          :text
#  is_converted  :boolean          default("false")
#  is_signed     :boolean          default("false")
#  is_presented  :boolean          default("false")
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
require 'csv_validator'
require 'xml_generator'

class Invoice < ActiveRecord::Base
  has_many :invoice_logs
  belongs_to :issuer
  belongs_to :customer

  validates :issuer_id, presence: true
  validates :customer_id, presence: true
  validates :invoice_serie, presence: true
  validates :invoice_num, presence: true
  validates :invoice_date, presence: true
  validates :amount, presence: true, numericality: true

  after_save :after_save
  after_find :after_find

  scope :signed, -> { where(is_signed: true) }
  scope :presented, -> { where(is_presented: true) }

  attr_reader :is_valid_xml
  attr_reader :header
  attr_reader :detail_list
  attr_reader :tax_list
  attr_reader :total
  attr_reader :installment_list

  def display_value
    "Customer: #{customer.name}. Subject: #{subject}. Amount: #{formatted_amount}"
  end

  def customer_name
    customer.name
  end

  def formatted_amount
    (total.nil? ? self.class.format_currency(0) : self.class.format_currency(total.total_invoice))
  end

  def self.format_currency(value)
    ActionController::Base.helpers.number_to_currency(
      value,locale: 'es',unit: "€", separator: ",", delimiter: ".", format: "%n %u")
  end

  def invoice_number
    (invoice_serie.blank? ? invoice_num : invoice_serie+"/"+invoice_num)
  end

  private

  def after_save
    if created_at == updated_at # best way of known it's INSERT, not UPDATE
      invoice_logs.create(
        action: "Issuer imported CSV and saved XML.",
      action_code: InvoiceLog::ACTION_SAVE_INVOICE)
    else
      if is_signed_changed?
        invoice_logs.create(
          action: "Issuer SIGNED invoice.",
        action_code: InvoiceLog::ACTION_INVOICE_SIGNED)
      elsif is_presented_changed?
        invoice_logs.create(
          action: "Issuer PRESENTED invoice.",
        action_code: InvoiceLog::ACTION_INVOICE_PRESENTED)
      else
        invoice_logs.create(
          action: "Issuer changed invoice. Changed fields: #{changed.to_s}",
        action_code: InvoiceLog::ACTION_INVOICE_CHANGED)
      end
    end
  end

  def after_find
    xml_generator = XMLgenerator::Generator.new
    validator = CSVvalidator::Validator.new(csv,xml_generator,self.issuer)
    @is_valid_xml = validator.valid?
    if @is_valid_xml
      @header           = xml_generator.header
      @detail_list      = xml_generator.detail_list
      @tax_list         = xml_generator.tax_list
      @total            = xml_generator.total
      @installment_list = xml_generator.installment_list
    end
  end
end

app/controllers/invoices_controller.rb
require 'csv_validator'
require 'xml_generator'

class InvoicesController < ApplicationController
  def new
    @page_title = 'Upload invoice'
    @issuer = current_issuer
    @invoice = @issuer.invoices.new
  end

  def create
    @issuer = current_issuer
    @invoice = @issuer.invoices.new
    if params[:invoice] == nil
      flash[:alert] = "Please, select a valid file"
      render('new')
      return
    end

    @invoice.csv = params[:invoice][:csv].read
    @xml_generator = XMLgenerator::Generator.new
    @validator = CSVvalidator::Validator.new(@invoice.csv,@xml_generator,@issuer)
    unless @validator.valid?
      flash[:alert] = "Please, check errors"
      # binding.pry
      @errors = @validator.errors.full_messages
      render('new')
      return
    end

    xml = @xml_generator.generate_xml

    @invoice.customer_id = @xml_generator.header.customer.id
    @invoice.invoice_serie = @xml_generator.header.invoice_serie
    @invoice.invoice_num = @xml_generator.header.invoice_number
    @invoice.invoice_date = @xml_generator.header.invoice_date
    @invoice.subject = @xml_generator.header.invoice_subject
    @invoice.amount = @xml_generator.total.total_invoice
    @invoice.xml = xml

    if @invoice.save
      flash[:notice] = "Invoice uploaded successfully"
      # render('show') # show just uploaded invoice
      redirect_to invoice_path(@invoice)
    else
      flash[:alert] = "Please, check errors"
      render('new')
    end
  end

  def update
    # not necessary at the moment
  end

  def edit
    # not necessary at the moment
  end

  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy
    flash[:notice] = 'Invoice Removed'
    redirect_to invoices_path
  end

  def index
    unless logged_in?
      redirect_to login_path
      return
    end

    flash[:alert] = nil

    @current_issuer = current_issuer
    @grid = InvoicesGrid.new(params[:invoices_grid]) do |scope|
      # params[:signed]
      options = {issuer_id: @current_issuer.id}
      where_like = ""

      options[:is_signed] = true if params[:signed].present?
      options[:is_presented] = true  if params[:presented].present?
      if params[:filter_text].present?
        where_like = 'customers.name ILIKE ?'
        like = params[:filter_text]
      end
      if where_like.blank?
        scope.where(options).page(params[:page])
      else
        scope.where([where_like,'%'+like+'%']).where(options).page(params[:page])
      end
    end
  end

  def show
    @invoice = Invoice.find(params[:id])
    unless @invoice.is_valid_xml
      flash[:alert] = "Internal error in this invoice"
      redirect_to invoices_path
    end
  end

  def download_csv
    invoice = Invoice.find(params[:id])
    file_name = build_tmp_file_name(invoice, "csv")
    send_file(
      file_name,
      type: "application/csv",
      x_sendfile: true
    )
    save_download_log(invoice,"CSV")
    # render "show"
  end

  def download_xml
    invoice = Invoice.find(params[:id])
    file_name = build_tmp_file_name(invoice, "xml")
    send_file(
      file_name,
      type: "application/xml",
      x_sendfile: true
    )
    save_download_log(invoice,"XML")
    # render "show"
  end

  def download_xsig
    invoice = Invoice.find(params[:id])
    file_name = build_tmp_file_name(invoice, "xsig")
    send_file(
      file_name,
      type: "application/xsig",
      x_sendfile: true
    )
    save_download_log(invoice,"XSIG")
    # render "show"
  end

  def sign
    @invoice = Invoice.find(params[:id])
    render 'sign'
  end

  def signing
    @invoice = Invoice.find(params[:id])
    signature = params[:invoice][:signature]
    is_error = signature != "abcdef"

    unless is_error
      # TODO: real signing
      @invoice.xsig = @invoice.xml + 
      "<signature>"+
      BCrypt::Password.create(signature)+
      "</signature>"
      
      @invoice.is_signed = true
    end

    if @invoice.save && !is_error
      flash[:notice] = "Invoice signed"
      redirect_to(action: 'show')
    else
      flash[:alert] = "Invalid signature"
      render('sign')
    end
  end

  def render_pdf
    # TODO: render pdf
    render 'shared/not_implemented'
    #save_download_log(invoice,"XML")
  end

  def send_to_admin
    # TODO: send to admin
    @invoice = Invoice.find(params[:id])
    @invoice.is_presented = true
    if @invoice.save
      flash[:notice] = "Invoice was sent successfully. Please wait while you are paid"
      redirect_to(action: 'show')
    else
      flash[:alert] = "Sorry, something was wrong"
      render 'show'
    end
  end

  private

  # FIXME: saves TWO times every log
  def save_download_log(invoice,format)
    invoice.invoice_logs.create(
      action: "Downloaded invoice in #{format} format.",
    action_code: InvoiceLog::ACTION_INVOICE_DOWNLOAD)
    invoice.invoice_logs.reload
  end

  def build_tmp_file_name(invoice, ext)
    field = invoice.attributes[ext]
    file_name = "#{Rails.root}/tmp/invoice_#{invoice.id}.#{ext}"
    File.open(file_name, 'w') { |file| file.write(field) }
    file_name
  end

  def edit_params
    params.require(:invoice).permit(:signature)
  end

end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/index.html.erb
<div class="row">
    <div class="container">
        <div class="col-md-6">
            <h3>Filter invoices</h3>
            <div id="filter_box" class="navbar-form navbar-left">
                <%=form_tag root_path, method: 'get', class: "navbar-form navbar-left", role: "search" %>
                    <%=text_field_tag :filter_text, params[:filter_text], class: 'form-control', placeholder: "Filter by customer name", id: "ed_filter_text" %>
                        <%=label_tag :signed, class: "checkbox inline submit_cancel" do %>
                            <%=check_box_tag :signed, "1", params[:signed].present?, class: 'form-control', id:"xb_signed_filter" %><span>Signed invoices</span>
                                <% end %>
                                    <%=label_tag :presented, class: "checkbox inline submit_cancel" do %>
                                        <%=check_box_tag :presented, "1", params[:presented].present?, class: 'form-control', id:"xb_presented_filter"%><span>Presented invoices</span>
                                            <% end %>
                                                <p>
                                                    <%=submit_tag "Apply filter", class: "btn btn-primary" %>
                                                    <button type="button" id="btn_clear_filter" class="btn btn-success">Clear filter</button>
                                                </p>
            </div>
        </div>
        <div class="col-md-3">
        </div>
        <div class="col-md-3">
          <div class="btn btn-danger" id="upload_button">
            <span class="glyphicon glyphicon-new-window"></span>
            <%=link_to 'Upload an invoice', new_invoice_path %>          
          </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div>
            <%=datagrid_form_for @grid, :method=> :get, :url => invoices_path%>

                <%=paginate(@grid.assets)%>
                    <%=datagrid_table @grid%>
                        <%=paginate(@grid.assets)%>
        </div>
    </div>
</div>

app/views/invoices/new.html.erb
<div class="row invoice_box">
    <div class="col-md-12">
        <h2>Select a CSV file for creating an invoice</h2>
      <div class="btn btn-success" id="need_help_button">
        <span class="glyphicon glyphicon-question-sign"></span>
        <%=link_to 'Need help? Explained here',  help_path %>          
      </div>
        <%=form_for @invoice, html: {multipart: true} do |f|%>
            <%=f.file_field :csv, class: 'btn btn-default', id: 'choose_file_btn'%>
                <div class="submit_cancel">
                    <%=f.submit "Submit", class: 'btn btn-primary'%>
                        <%=link_to "Cancel", invoices_path, class: 'btn btn-default'%>
                </div>
                <%end%>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <%if flash[:alert]%>
            <div class="row invoice_box error_box">
                <div class="col-md-12">
                    <% if @errors == nil %>
                            <div class="row">
                                <p>No valid file selected</p>
                            </div>
                    <% else %>
                        <%@errors.each do |error|%>
                            <div class="row">
                                <%=error%>
                            </div>
                            <%end%>
                    <% end %>
                </div>
            </div>
            <%end%>
    </div>
</div>

app/views/invoices/show.html.erb
<div class="continer">
    <div class="row invoice_show">
        <div class="col-md-9 invoice_box">
            <div>
                <table class="table">
                    <tbody>
                        <tr>
                            <td>Customer</td>
                            <td>
                                <h2 class="lead"><%=@invoice.customer_name%></h2>
                            </td>
                        </tr>
                        <tr>
                            <td>Subject</td>
                            <td>
                                <%=@invoice.header.invoice_subject%>
                            </td>
                        </tr>
                        <tr>
                            <td>Processing unit</td>
                            <td>
                                <%=@invoice.header.customer_processing_unit%>
                            </td>
                        </tr>
                        <tr>
                            <td>Accounting service</td>
                            <td>
                                <%=@invoice.header.customer_accounting_service%>
                            </td>
                        </tr>
                        <tr>
                            <td>Management unit</td>
                            <td>
                                <%=@invoice.header.customer_processing_unit%>
                            </td>
                        </tr>
                        <tr>
                            <td>Invoice number</td>
                            <td>
                                <%=@invoice.invoice_number%>
                            </td>
                        </tr>
                        <tr>
                            <td>Invoice date</td>
                            <td>
                                <%=@invoice.invoice_date.to_s(:spanish)%>
                            </td>
                        </tr>
                        <tr>
                            <td>Invoice amount</td>
                            <td class="lead">
                                <%=@invoice.formatted_amount%>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <%unless @invoice.is_signed || @invoice.is_presented%>
                    <p class="small">
                        <%=link_to 'Delete invoice', invoice_path(@invoice), class: "text-danger", method: :delete, data: {confirm: 'Are you sure?'}%>
                    </p>
                    <%end%>
                        <h3>
              <%if @invoice.is_signed && !@invoice.is_presented%>
              <div class="signed_class"><span class="glyphicon glyphicon-ok"></span> Signed</div>
              <%end%>
              <%if @invoice.is_presented%>
              <div class="presented_class"><span class="glyphicon glyphicon-send"></span> Sent</div>
              <%end%>
            </h3>
            </div>
        </div>
        <div class="col-md-3 vertical_buttons_group">
            <ul class="list-unstyled">
                <li>
                    <div class="btn btn-success action_button my_button">
                        <span class="fa fa-file-excel-o"></span>
                        <%=link_to 'Download original CSV file', invoices_download_csv_path(@invoice)%>
                    </div>
                </li>
                <li>
                    <div class="btn btn-warning action_button my_button">
                        <span class="glyphicon glyphicon-save-file"></span>
                        <%=link_to 'Download unsigned XML file', invoices_download_xml_path(@invoice)%>
                    </div>
                </li>
                <li>
                    <div class="btn btn-danger action_button my_button" <%=(@invoice.is_signed ? 'disabled="disabled"' : '')%> >
                        <span class="glyphicon glyphicon-ok"></span>
                        <%=link_to 'Sign invoice', invoices_sign_path(@invoice)%>
                    </div>
                </li>
                <li>
                    <div class="btn btn-primary action_button my_button" <%=(@invoice.is_signed ? '' : 'disabled="disabled"')%> >
                        <span class="fa fa-file-text-o"></span>
                        <%=link_to 'Download XSIG signed file', invoices_download_xsig_path(@invoice)%>
                    </div>
                </li>
                <li>
                    <div class="btn btn-danger action_button my_button" <%=(@invoice.is_signed ? '' : 'disabled="disabled"')%> >
                        <span class="glyphicon glyphicon-send"></span>
                        <%=link_to 'Send to administration', invoices_send_to_admin_path(@invoice)%>
                    </div>
                </li>
                <li>
                    <div class="btn btn-warning action_button my_button">
                        <span class="fa fa-file-pdf-o"></span>
                        <%=link_to 'Download as PDF', invoices_render_pdf_path(@invoice)%>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-md-9 invoice_box log_box">
            <%@invoice.invoice_logs.each do |log|%>
                <div class="row">
                    <mark>
                        <%=log.created_at%>
                    </mark><span>: <%=log.action%></span>
                </div>
                <%end%>

        </div>
    </div>
</div>

app/views/invoices/sign.html.erb
<% provide(:title, "Signing invoice") %>


<div class="row">
  <div class="container">
  <div class="col-md-6 col-md-offset-3">
    <h1>Sign an invoice</h1>
    <h3><%=@invoice.customer_name%></h3>
    <h4><%=@invoice.subject%></h4>
    <h4><span id="invoice_number" class="lead">Invoice: <%=@invoice.invoice_number%></span><span>Date: <%=@invoice.invoice_date.to_s(:spanish)%></span></h4>
    <h3><%=@invoice.formatted_amount%></h3>
    <%= form_for(:invoice, url: invoices_sign_path) do |f| %>

      <%= f.label :signature %>
      <%= f.password_field :signature, class: 'form-control' %>

      <%= f.submit "Sign", class: "btn btn-danger submit_cancel" %>
      <%=link_to "Cancel", invoice_path(@invoice), class: 'btn btn-default submit_cancel'%>
    <% end %>
    </div>
  </div>
</div>