config/routes.rb
Rails.application.routes.draw do
  root 'invoices#index'

  get 'help' => 'help#index'

  get 'customers', to: 'customers#index'

  get 'invoices/:id/download_csv', to: 'invoices#download_csv', as: 'invoices_download_csv'
  get 'invoices/:id/download_xml', to: 'invoices#download_xml', as: 'invoices_download_xml'
  get 'invoices/:id/download_xsig', to: 'invoices#download_xsig', as: 'invoices_download_xsig'
  get 'invoices/:id/send', to: 'invoices#send_to_admin', as: 'invoices_send_to_admin'
  get 'invoices/:id/sign', to: 'invoices#sign', as: 'invoices_sign'
  post 'invoices/:id/sign', to: 'invoices#signing', as: 'invoices_signing'
  get 'invoices/:id/render_pdf', to: 'invoices#render_pdf', as: 'invoices_render_pdf'
  resources :invoices, except: [:update, :edit]

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>
        <%=@page_title ? @page_title : 'Invoices' %> | Facturem</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track'=> true %>
        <%=javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
            <%=csrf_meta_tags %>
</head>

<body>

<nav class="header-nav navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%=link_to 'Facturem', root_path, class: "navbar-brand" %>
      <%if logged_in?%>
        <span class="navbar-text glyphicon glyphicon-briefcase company_name"></span>
        <p class="navbar-text company_name"><%="#{@current_issuer.tax_id} | #{@current_issuer.company_name}" %></p>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      <%end%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <%if logged_in?%>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        <li class="<%=(params[:controller] == 'invoices' && params[:action] == 'index') ? 'active' : '' %>">
            <%=link_to 'Your invoices', root_path, class: "toggle_link img-rounded" %>
        </li>
        <li class="<%=(params[:controller] == 'invoices' && params[:action] == 'new') ? 'active' : '' %>">
            <%=link_to 'Upload an invoice', new_invoice_path, class: "toggle_link img-rounded" %>
        </li>
        <li class="<%=(params[:controller] == 'customers') ? 'active' : '' %>">
            <%=link_to 'Customers', customers_path, class: "toggle_link img-rounded" %>
        </li>
        <li class="<%=params[:controller] == 'help' ? 'active' : '' %>">
            <%=link_to 'How to create CSV files', help_path, class: "toggle_link img-rounded" %>
        </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%=link_to "Log out", logout_path, method: :delete %>
          </li>
        </ul>
      </div>
    <%end%>
  </div>
</nav>
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <!-- Alerts & Messages -->
                <% if flash[:notice] %>
                    <div class="alert alert-success">
                        <%=flash[:notice] %>
                    </div>
                    <% end %>

                        <% if flash[:alert] %>
                            <div class="alert alert-danger">
                                <%=flash[:alert] %>
                            </div>
                            <% end %>
                                <%=yield%>
            </div>
        </div>
    </div>
</section>

<footer class="footer navbar-fixed-bottom">
    <div class="container legal">
        <p>Made at Ironhack Jan-March 2015 | <a href="#">Legal info</a></p>
    </div>
</footer>

</body>

</html>